export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOAD = 'LOGIN_LOAD';
export const AUTH_FAIL = 'AUTH_FAIL';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_FAIL = 'UPDATE_FAIL';
export const NCLIENT_FAIL = 'NCLIENT_FAIL';
// Action to loading all the clients from DB
export const GET_CLIENTS = 'GET_CLIENTS';
export const LOGOUT = 'LOGOUT';
// Account and Notifications Actions
export const ACCOUNT = 'ACCOUNT';
export const NOTIFICATIONS = 'NOTIFICATIONS';
export const NAV = 'NAV';
export const NAV_SETTING = 'NAV_SETTING';
export const CLOSE = 'CLOSE';
export const CALC = 'CALC';
